/**
 * Fields the caller supplies to logRequest. ts is generated by the logger
 * itself so the timestamp always reflects the exact moment of emission —
 * callers should not synthesise it.
 */
export interface RequestLogFields {
  reqId: string;
  method: string;
  path: string;
  /** Verdict string — will be typed against the domain Verdict enum in Phase 2. */
  verdict: string;
  latencyMs: number;
}

/**
 * Emits a single JSON log line to stdout for every handled request.
 *
 * Output shape (all fields required by the Phase 1 spec):
 *   { ts, reqId, method, path, verdict, latencyMs }
 *
 * The no-console rule is suppressed here intentionally — this is the one
 * place in the codebase that is allowed to call console.log directly.
 * All other code should call logRequest instead.
 */
export function logRequest(fields: RequestLogFields): void {
  // eslint-disable-next-line no-console
  console.log(
    JSON.stringify({
      ts: new Date().toISOString(),
      reqId: fields.reqId,
      method: fields.method,
      path: fields.path,
      verdict: fields.verdict,
      latencyMs: fields.latencyMs,
    }),
  );
}
